version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_NAME=ordernimbus_wp
      - DB_USER=wp_user
      - DB_PASSWORD=wp_password
      - DB_HOST=db
      - WORDPRESS_URL=http://localhost:8080
      - WORDPRESS_TITLE=OrderNimbus - Enterprise AI-Powered Sales Forecasting
      - WORDPRESS_ADMIN_USER=admin
      - WORDPRESS_ADMIN_PASSWORD=admin_password
      - WORDPRESS_ADMIN_EMAIL=admin@ordernimbus.com
      - WP_AUTH_KEY=your-auth-key-here
      - WP_SECURE_AUTH_KEY=your-secure-auth-key-here
      - WP_LOGGED_IN_KEY=your-logged-in-key-here
      - WP_NONCE_KEY=your-nonce-key-here
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html/wp-content/uploads
    restart: unless-stopped
    networks:
      - wp-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ordernimbus_wp
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - wp-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  wordpress_data:
  db_data:

networks:
  wp-network:
    driver: bridge